cmake_minimum_required(VERSION 3.8)
project(plc_io_modbus)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(std_msgs REQUIRED)
find_package(std_srvs REQUIRED)
add_executable(plc_io_modbus src/node.cpp)
target_compile_features(plc_io_modbus PRIVATE cxx_std_17)
target_compile_options(plc_io_modbus PRIVATE -Wall -Wextra -Wpedantic)
ament_target_dependencies(plc_io_modbus rclcpp std_msgs std_srvs)
install(TARGETS plc_io_modbus DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY config DESTINATION share/${PROJECT_NAME})
ament_package()
