cmake_policy(SET CMP0053 NEW)

if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED BUS_CONFIG_PATH)
  message(FATAL_ERROR "INPUT_FILE, OUTPUT_FILE, and BUS_CONFIG_PATH are required")
endif()

file(READ "${INPUT_FILE}" BUS_CONTENT)
string(REGEX MATCHALL "@BUS_CONFIG_PATH@" PATH_MATCHES "${BUS_CONTENT}")
list(LENGTH PATH_MATCHES PATH_MATCH_COUNT)
if(NOT PATH_MATCH_COUNT EQUAL 1)
  message(FATAL_ERROR "Expected exactly one @BUS_CONFIG_PATH@, found ${PATH_MATCH_COUNT}")
endif()
string(REPLACE "@BUS_CONFIG_PATH@" "${BUS_CONFIG_PATH}" BUS_CONTENT "${BUS_CONTENT}")
file(WRITE "${OUTPUT_FILE}" "${BUS_CONTENT}")
