"""Launch-time configuration helpers for the RT-Control composition."""

from .hardware_composition import (
    CanopenComposition,
    CanopenNode,
    EthercatAxis,
    EthercatComposition,
    HardwareComposition,
    HardwareCompositionError,
    load_hardware_variants,
    validate_controller_compatibility,
    variant_descriptor_path,
)
from .machine_profile import (
    BusLayout,
    GroupReference,
    MachineManifest,
    MachineProfileError,
    ModeGroup,
    ModuleSpec,
    PhysicalLayout,
    PhysicalProfile,
    ScopeSpec,
    SelectedHardware,
    load_machine_manifest,
    select_hardware,
)

__all__ = [
    "CanopenComposition",
    "CanopenNode",
    "EthercatAxis",
    "EthercatComposition",
    "HardwareComposition",
    "HardwareCompositionError",
    "load_hardware_variants",
    "validate_controller_compatibility",
    "variant_descriptor_path",
    "BusLayout",
    "GroupReference",
    "MachineManifest",
    "MachineProfileError",
    "ModeGroup",
    "ModuleSpec",
    "PhysicalLayout",
    "PhysicalProfile",
    "ScopeSpec",
    "SelectedHardware",
    "load_machine_manifest",
    "select_hardware",
]
